In [1]:
import numpy as np

In [17]:
Q_TABLE = np.load('A0_5526538_QTABLE_40.npy')

In [51]:
state = np.array([0,0,0,0])
action = 2

In [52]:
index = np.hstack((state,action))

In [59]:
Q_TABLE[tuple(state)].max()

-10.017533302307129

In [62]:
a=tuple([2,5,6])

In [63]:
b=tuple([1,4,5])

In [65]:
x = np.hstack((a,b))

In [66]:
x

array([2, 5, 6, 1, 4, 5])

In [21]:
X = np.random.randint(10,size=(5,7))
print(X)

[[9 7 3 9 6 1 7]
 [9 1 3 1 8 0 7]
 [1 1 5 3 7 6 1]
 [3 4 3 4 5 0 0]
 [1 7 2 4 0 6 5]]


In [22]:
print(X[indices,:])

[[3 4 3 4 5 0 0]
 [9 1 3 1 8 0 7]]


In [24]:
a = X[0]

In [25]:
a

array([9, 7, 3, 9, 6, 1, 7])

In [26]:
a[2:-1]

array([3, 9, 6, 1])

In [27]:
a[-1]

7