In [4]:
import numpy as np

In [19]:
indices = np.random.choice(5,2)
print(indices)

[3 1]


In [21]:
X = np.random.randint(10,size=(5,7))
print(X)

[[9 7 3 9 6 1 7]
 [9 1 3 1 8 0 7]
 [1 1 5 3 7 6 1]
 [3 4 3 4 5 0 0]
 [1 7 2 4 0 6 5]]


In [22]:
print(X[indices,:])

[[3 4 3 4 5 0 0]
 [9 1 3 1 8 0 7]]


In [24]:
a = X[0]

In [25]:
a

array([9, 7, 3, 9, 6, 1, 7])

In [26]:
a[2:-1]

array([3, 9, 6, 1])

In [27]:
a[-1]

7